services:
  web:
    build: .
    ports:
    - "85:80"
  redis:
    image: "redis:alpine"
  python:
    ports: 
    - 5002:5002
    depends_on: 
    - redis
    environment: 
      REDIS_HOST: redis
    image: my-python
