apiVersion: v1
kind: Pod
metadata:
  name: host-path-pod
  labels:
    name: host-path-pod
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: workshop-worker
  volumes:
  - name: host-path
    hostPath:
      path: /etc
  containers:
  - name: host-path-pod-bb
    image: busybox
    command: ['sh', '-c', 'echo running! && sleep 3600']
    volumeMounts:
    - name: host-path
      mountPath: /pod-empty/
    resources: {}
